name: Deploy to Render

on: 
  push:
    branches: 
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deploy from render
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}

